# Markdownlint configuration

# Default state for all rules
default: true

# Override specific rules
MD001: false  # Heading increment - sometimes we need to jump levels
MD013: false  # Line length - disable for documentation files
MD024: false  # No duplicate headings - same headings in different sections are OK
MD025: false  # Single title - multiple H1s can be intentional
MD029: false  # Ordered list prefix - auto-numbering is fine
MD033: false  # Inline HTML - needed for some formatting
MD036: false  # Emphasis used instead of heading - sometimes intentional
MD040: false  # Fenced code blocks should have a language - not always needed
MD046: false  # Code block style - allow both fenced and indented
MD051: false  # Link fragments - may not always match exactly
