name: ✨ Feature Request
description: Suggest a new feature or improvement for NetworkX MCP Server
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! ✨
        
        Help us understand your idea and its potential impact on the NetworkX MCP Server.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please verify that you have completed the following
      options:
        - label: I have searched existing issues and discussions for similar feature requests
          required: true
        - label: I have reviewed the [roadmap](https://github.com/brightliu/networkx-mcp-server/projects) to see if this is already planned
          required: true
        - label: I have considered if this could be implemented as a plugin or extension
          required: true

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What type of feature is this?
      options:
        - "New MCP Tool"
        - "New Algorithm"
        - "Visualization Enhancement"
        - "Performance Improvement"
        - "Developer Experience"
        - "Documentation"
        - "Security Feature"
        - "Enterprise Feature"
        - "Machine Learning"
        - "Import/Export Format"
        - "Other"
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? Why is it needed?
      placeholder: |
        Describe the problem or limitation you're experiencing:
        - What can't you do today?
        - What's the impact of not having this feature?
        - Who would benefit from this feature?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: What would you like to see implemented?
      placeholder: |
        Describe your ideal solution:
        - How should it work?
        - What should the API look like?
        - Any specific requirements or constraints?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative approaches?
      placeholder: |
        Describe alternative solutions you've considered:
        - Other ways to solve the same problem
        - Existing tools or workarounds
        - Why your proposed solution is better

  - type: textarea
    id: example
    attributes:
      label: Usage Example
      description: Show how the feature would be used
      render: python
      placeholder: |
        # Example of how the feature would be used
        
        # Current approach (if any):
        # current_method()
        
        # Proposed approach:
        # new_feature_method()

  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      description: How important is this feature to you?
      options:
        - "Low - Nice to have"
        - "Medium - Would improve my workflow"
        - "High - Blocking my current project"
        - "Critical - Essential for production use"
    validations:
      required: true

  - type: dropdown
    id: complexity
    attributes:
      label: Estimated Complexity
      description: How complex do you think this feature would be to implement?
      options:
        - "Low - Small change or addition"
        - "Medium - Moderate development effort"
        - "High - Significant implementation required"
        - "Very High - Major architectural changes"
        - "I'm not sure"

  - type: textarea
    id: benefits
    attributes:
      label: Expected Benefits
      description: What benefits would this feature provide?
      placeholder: |
        List the expected benefits:
        - Performance improvements
        - Easier workflow
        - New capabilities enabled
        - Better user experience
        - etc.

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Ideas
      description: Do you have ideas about how this could be implemented?
      placeholder: |
        If you have technical ideas about implementation:
        - Relevant libraries or algorithms
        - Similar features in other tools
        - Potential challenges or considerations
        - Performance implications

  - type: textarea
    id: compatibility
    attributes:
      label: Compatibility Considerations
      description: Are there any compatibility concerns?
      placeholder: |
        Consider compatibility with:
        - Current API (breaking changes?)
        - Different Python versions
        - MCP specification
        - NetworkX versions
        - Performance impact on existing features

  - type: input
    id: related-tools
    attributes:
      label: Related Tools/Libraries
      description: Are there similar features in other tools?
      placeholder: "NetworkX, igraph, SNAP, Gephi, etc."

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Anything else you'd like to add?
      placeholder: |
        - Links to relevant research papers
        - Screenshots or mockups
        - Real-world use cases
        - Performance requirements
        - etc.

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Are you interested in contributing to this feature?
      options:
        - label: I would like to implement this feature myself
          required: false
        - label: I can help with testing and validation
          required: false
        - label: I can provide domain expertise
          required: false
        - label: I can help with documentation
          required: false

  - type: checkboxes
    id: funding
    attributes:
      label: Funding/Sponsorship
      description: Is there organizational support for this feature?
      options:
        - label: My organization would be interested in sponsoring this feature
          required: false
        - label: This feature is needed for a commercial project
          required: false
        - label: This is for academic research
          required: false