apiVersion: apps/v1
kind: Deployment
metadata:
  name: networkx-mcp-server
  namespace: default
  labels:
    app: networkx-mcp
    environment: production
    version: "stable"
spec:
  replicas: 3  # Production scale
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: networkx-mcp
      environment: production
  template:
    metadata:
      labels:
        app: networkx-mcp
        environment: production
        version: "stable"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
        prometheus.io/path: "/metrics"
        deployment.kubernetes.io/revision: "${GITHUB_SHA:0:8}"
    spec:
      containers:
      - name: mcp-server
        image: ${IMAGE}
        imagePullPolicy: Always
        command: ["python", "-m", "networkx_mcp", "--jsonrpc"]
        
        ports:
        - name: health
          containerPort: 8080
        - name: metrics
          containerPort: 9090
          
        env:
        - name: ENVIRONMENT
          value: "production"
        - name: LOG_LEVEL
          value: "INFO"
        - name: LOG_FORMAT
          value: "json"
        - name: STORAGE_BACKEND
          value: "redis"
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: redis-credentials
              key: url
        - name: AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              name: mcp-auth
              key: token
        - name: MAX_CONCURRENT_CONNECTIONS
          value: "50"  # Production limits from testing
        - name: MAX_GRAPH_SIZE_NODES
          value: "10000"
        - name: MAX_MEMORY_MB
          value: "2048"
        - name: ENABLE_AUTH
          value: "true"
        - name: TRACING_ENABLED
          value: "true"
        - name: JAEGER_ENDPOINT
          value: "jaeger-collector:14268"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: DEPLOYMENT_VERSION
          value: "${GITHUB_SHA:0:8}"
          
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
            
        livenessProbe:
          httpGet:
            path: /health
            port: health
          initialDelaySeconds: 20
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
          
        readinessProbe:
          httpGet:
            path: /ready
            port: health
          initialDelaySeconds: 10
          periodSeconds: 15
          timeoutSeconds: 3
          failureThreshold: 2
          
        startupProbe:
          httpGet:
            path: /startup
            port: health
          initialDelaySeconds: 15
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 10
          
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1000
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
            
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: cache
          mountPath: /app/cache
        - name: logs
          mountPath: /app/logs
          
      securityContext:
        fsGroup: 1000
        
      volumes:
      - name: tmp
        emptyDir:
          sizeLimit: 200Mi
      - name: cache
        emptyDir:
          sizeLimit: 500Mi
      - name: logs
        emptyDir:
          sizeLimit: 200Mi
          
      terminationGracePeriodSeconds: 45
      
      # Production affinity rules
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - networkx-mcp
              topologyKey: kubernetes.io/hostname

---
# Production Service
apiVersion: v1
kind: Service
metadata:
  name: networkx-mcp-service
  labels:
    app: networkx-mcp
    environment: production
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9090"
spec:
  selector:
    app: networkx-mcp
    environment: production
  ports:
  - name: health
    port: 8080
    targetPort: health
  - name: metrics
    port: 9090
    targetPort: metrics
  type: ClusterIP

---
# Production Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: networkx-mcp-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/rate-limit: "100"
    nginx.ingress.kubernetes.io/rate-limit-window: "1m"
spec:
  tls:
  - hosts:
    - api.mcp.example.com
    secretName: mcp-api-tls
  rules:
  - host: api.mcp.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: networkx-mcp-service
            port:
              number: 8080

---
# ServiceMonitor for production metrics
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: networkx-mcp-metrics
  labels:
    app: networkx-mcp
    environment: production
spec:
  selector:
    matchLabels:
      app: networkx-mcp
      environment: production
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics
    timeout: 15s
  jobLabel: app