apiVersion: v2
name: networkx-mcp
description: |
  Enterprise-grade NetworkX MCP Server for graph operations and analysis.
  Includes comprehensive monitoring, security, and scalability features.

type: application
version: 2.0.0
appVersion: "2.0.0"

keywords:
  - networkx
  - mcp
  - graph
  - analytics
  - python
  - microservice

home: https://github.com/your-org/networkx-mcp-server
sources:
  - https://github.com/your-org/networkx-mcp-server

maintainers:
  - name: Your Organization
    email: team@yourorg.com
    url: https://yourorg.com

annotations:
  category: Analytics
  licenses: MIT

dependencies:
  - name: redis
    version: "17.15.6"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
  
  - name: postgresql
    version: "12.12.10"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
  
  - name: prometheus
    version: "25.8.0"
    repository: "https://prometheus-community.github.io/helm-charts"
    condition: monitoring.prometheus.enabled
  
  - name: grafana
    version: "7.0.19"
    repository: "https://grafana.github.io/helm-charts"
    condition: monitoring.grafana.enabled